### ISSUE TITLE
Add build instructions to README

### ISSUE THREAD

**Issue by colinkiama** [vanat/vanat#13]
## Benefits:
- The main instructions the user needs to build the project is right there
- Contributors who have just implemented a feature/added a dependency can add requirements without having to completely switch to a different repo
- Easier to maintain than the website.
- Better availability: The vanat website can go down but this repo and its README instructions can survive through mirrors, forks and clones.

**Comment by robertsanseries** [comment]
@colinkiama  I really intend to leave this information on the website. Following the example of other repositories such as:

https://github.com/composer/composer
https://github.com/npm/npm
https://github.com/gradle/gradle
https://github.com/pypa/pip

About the site unavailability: Fortunately I use github pages.

Anyway, I'll also put the instructions on the repository's wiki (https://github.com/vanat/vanat/wiki).

Thanks for the feedback.
